aws-solutions/amazon-s3-glacier-refreezer

.github/workflows/pipeline-workflow.yml, .github/workflows/pull-request-workflow.yml
This PR adds the default github action workflows for pipelines integration.
=> Bootstrap workflows

pyproject.toml, source/refreezer/infrastructure/stack.py, source/refreezer/pipeline/stack.py, source/tests/integration/infrastructure/conftest.py, source/tests/integration/infrastructure/test_async_facilitator.py, source/tests/integration/infrastructure/test_output_bucket.py, source/tests/unit/infrastructure/test_stack.py
Create the bucket to store the restored vault. This will eventually be made configurable.
=> GRF - Create output bucket

source/refreezer/infrastructure/stack.py, source/refreezer/pipeline/stack.py, source/tests/integration/infrastructure/test_buckets.py, source/tests/unit/infrastructure/test_stack.py
Create the bucket that will be used for storing the inventory (and the Glue output after it's sorted). This will eventually be made configurable in a future task.
=> Create Inventory bucket

source/refreezer/application/handlers.py, source/refreezer/infrastructure/stack.py, source/refreezer/pipeline/stack.py, source/tests/integration/infrastructure/test_chunk_retrieval_lambda.py, source/tests/unit/infrastructure/test_stack.py
*Description of changes:
- Adds the skeleton for the chunk retrieval lambda
- Adds base integration test for lambda invokation and base unit test for cdk resource creation
=> Create chunk retrieval lambda skeleton

source/refreezer/application/chunking/inventory.py, source/refreezer/application/handlers.py, source/refreezer/infrastructure/stack.py, source/refreezer/pipeline/stack.py, source/tests/integration/infrastructure/test_inventory_chunk_determination_lambda.py, source/tests/unit/application/test_inventory_generate_chunk_array.py, source/tests/unit/infrastructure/test_stack.py
- Implement inventory retrieval chunk determination lambda
- Add Unit tests and integration tests
=> Implement inventory retrieval chunk determination lambda

source/refreezer/application/mocking/initiate_job.py, source/refreezer/infrastructure/stack.py, source/refreezer/pipeline/stack.py, source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py, source/tests/unit/infrastructure/test_stack.py
Build InitiateJob task using Step Function SDK integration
=> Get inventory - Build InitiateJob task

source/refreezer/application/model/facilitator.py, source/tests/unit/application/model/test_facilitator_model.py
https://app.asana.com/0/1202938635037719/1204131945299333/f
=> GRF - Async Facilitator Lambda - Data Model

.gitignore, pyproject.toml, source/refreezer/application/db_accessor/dynamoDb_accessor.py, source/tests/unit/application/db_accessor/test_db_accessor.py, source/tests/unit/conftest.py
https://app.asana.com/0/1202938635037719/1204131945299326/f
=> GRF - Async Facilitator Lambda - Data Access Layer 

source/refreezer/application/handlers.py, source/refreezer/infrastructure/stack.py, source/tests/unit/infrastructure/test_stack.py
Add the skeleton for Inventory Chunk Download Lambda and add unit test cases.
=> Add Inventory Chunk Download Lambda Skeleton plus unit tests

source/refreezer/application/glacier_service/glacier_apis.py, source/refreezer/application/glacier_service/glacier_apis_factory.py, source/refreezer/application/mocking/mock_glacier_apis.py
Add Glacier service mocking mechanism to be able to mimic Glacier APIs within lambda code
=> Add Glacier service mocking mechanism for Lambdas

source/refreezer/application/archive_transfer/facilitator.py, source/refreezer/application/archive_transfer/upload.py, source/refreezer/application/handlers.py, source/refreezer/infrastructure/stack.py, source/tests/unit/application/archive_transfer/test_facilitator.py, source/tests/unit/infrastructure/test_stack.py
*Issue #, if available: [Download](https://app.asana.com/0/1202938635037719/1203960890664563/f), [Upload](https://app.asana.com/0/1202938635037719/1203960903818534/f)
- Adds working upload/download
- Adds unit tests for facilitator module
=> Add chunk copy lambda up/download functionality

.viperlightignore, pyproject.toml, source/refreezer/application/facilitator/processor.py, source/refreezer/application/handlers.py, source/tests/unit/application/facilitator/test_processor.py, source/tests/unit/conftest.py, source/tests/unit/infrastructure/test_stack.py
[*Issue #, if available:*
](https://app.asana.com/0/1202938635037719/1203689150582176/f)
=> GRF - Async facilitator Lambda - feature/kamyarz

source/refreezer/infrastructure/stack.py
Grant Async facilitator Lambda necessary permissions for SendTaskSuccess/Failure
=> Grant Async facilitator Lambda permissions for SendTaskSuccess/Failure

source/refreezer/infrastructure/stack.py, source/tests/unit/infrastructure/test_stack.py
- Disable SNS Topic server-side encryption
- Grant SNS:Publish to Glacier principal
=> Adjust SNS access permissions and SSE to allow Glacier notifications

source/refreezer/application/handlers.py, source/refreezer/infrastructure/stack.py, source/tests/unit/infrastructure/test_stack.py
*Issue #, if available: [Asana](https://app.asana.com/0/1202938635037719/1204056345804294/f)
*Description of changes:* Adds the skeleton for the validation lambda
=> Add chunk validation lambda skeleton

source/refreezer/infrastructure/glue_helper/glue_sfn_update.py, source/tests/unit/infrastructure/glue_helper/test_glue_sfn_update.py
https://app.asana.com/0/1202938635037719/1203859596572558/f
=> Glue-StepFunction additional construct

source/refreezer/infrastructure/stack.py, source/refreezer/pipeline/stack.py, source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py, source/tests/unit/infrastructure/test_stack.py
Build the skeleton for the initiate retrieval state machine, using PASS states.
=> Build the skeleton for the initiate retrieval state machine

source/refreezer/infrastructure/stack.py, source/refreezer/pipeline/stack.py, source/tests/integration/infrastructure/test_retrieve_archive_step_function.py, source/tests/unit/infrastructure/test_stack.py
Build the skeleton for the retrieve archive state machine.
=> Build the skeleton for the retrieve archive state machine

source/refreezer/application/handlers.py, source/refreezer/infrastructure/stack.py, source/tests/integration/infrastructure/test_archive_chunk_determination_lambda.py
https://app.asana.com/0/1202938635037719/1204056345804301/f
I'm waiting for PR 100 to be approved to integrate the Archive Chunk determination into the Archive State Machine code, but it's important to keep submitting PRs.
I'll add the Lambda Task and proper Integration Tests once PR 100 is approved.
=> Archive chunk determination skeleton

pyproject.toml, source/refreezer/infrastructure/stack.py, source/tests/unit/infrastructure/test_stack.py
https://app.asana.com/0/1202938635037719/1204080239615919/f
=> GRF - Generate Glue Job CDK for ordering the vault inventory

source/refreezer/application/mocking/notify_sns.py, source/refreezer/infrastructure/stack.py, source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py, source/tests/unit/infrastructure/test_stack.py
- Write to Dynamo an item of JobId, TaskToken
- Use waitForTaskToken integration pattern (Step Function SDK integration)
=> Get inventory - Build Dynamodb PutItem task

pyproject.toml, source/refreezer/application/handlers.py, source/refreezer/application/model/events.py
*Issue #, if available:* [Asana](https://app.asana.com/0/1202938635037719/1204292304491409/f)
*Description of changes:* 
- Adds Event Typing to our Lambda Handlers
=> Add Lambda Handler Event Typing

source/refreezer/infrastructure/stack.py, source/refreezer/pipeline/stack.py, source/tests/integration/infrastructure/test_glacier_object_retrieval_dynamodb.py, source/tests/unit/infrastructure/test_stack.py
https://app.asana.com/0/1202938635037719/1203922468885149/f
=> DynamoDB CDK for Archive Parts Table

source/refreezer/infrastructure/stack.py
=> update for suppression nag

source/refreezer/infrastructure/stack.py, source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py
Add ItemsPath to step function initiate retrieval map for integration tests
=> Add items path to sfn initiate retrieval map

source/refreezer/infrastructure/glue_helper/glue_sfn_update.py, source/tests/unit/infrastructure/glue_helper/test_glue_sfn_update.py
https://app.asana.com/0/1202938635037719/1203922469484730/f
=> GRF - Get inventory - validate after Glue sort

source/refreezer/infrastructure/stack.py, source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py, source/tests/unit/infrastructure/test_stack.py
https://app.asana.com/0/1202938635037719/1204196022036762/f
Initiate the workflow and store the JobID and ArchiveID to the DynamoDB table
=> Initiate Workflow PutItem

source/refreezer/application/chunking/archive.py, source/tests/unit/application/chunking/test_archive_generate_chunk_array.py, source/tests/unit/application/chunking/test_trim_inventory_chunk.py
Implement Archive chunk array creation lambda logic
=> Implement Archive chunk array creation lambda logic

source/refreezer/infrastructure/glue_helper/glue_sfn_update.py, source/refreezer/infrastructure/stack.py, source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py, source/tests/unit/infrastructure/glue_helper/test_glue_sfn_update.py, source/tests/unit/infrastructure/test_stack.py
https://app.asana.com/0/1202938635037719/1203859596572560/f
=> GRF - Add Glue job to the inventory retrieval workflow

source/refreezer/application/chunking/inventory.py, source/refreezer/application/facilitator/processor.py, source/refreezer/application/glacier_s3_transfer/download.py, source/refreezer/application/glacier_s3_transfer/facilitator.py, source/refreezer/application/util/exceptions.py, source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py, source/tests/unit/application/chunking/test_inventory_generate_chunk_array.py, source/tests/unit/application/glacier_s3_transfer/test_download.py, source/tests/unit/application/glacier_s3_transfer/test_facilitator.py
*Issue #, if available:* [Asana](https://app.asana.com/0/1202938635037719/1204341388364945/f)
- Adds a few custom exceptions to replace the `raise Exception(string_literal)` we had going on in some places
- Does *not* add decorators to be used to wrap AWS exceptions. If this is something we want, we can also get that added.
=> Add custom exceptions

source/refreezer/infrastructure/stack.py, source/tests/unit/infrastructure/test_stack.py
Fix: Remove the cyclic link between glue state and validate multipart state
=> Remove the cyclic link between glue state and validate multipart state

source/refreezer/application/glacier_s3_transfer/facilitator.py, source/refreezer/application/glacier_s3_transfer/upload.py, source/refreezer/application/handlers.py, source/refreezer/application/model/events.py, source/refreezer/application/model/responses.py, source/tests/unit/application/glacier_s3_transfer/test_facilitator.py
*Issue #, if available: [Asana](https://app.asana.com/0/1202938635037719/1204098877654449/f)
- Implements the lambda which will download the inventory byte ranges from Glacier and upload it to S3
- Updates the typing of responses from the previously mentioned lambda handlers.
=> Implement Inventory Download Lambda

source/refreezer/infrastructure/distributed_map.py, source/refreezer/infrastructure/stack.py, source/tests/integration/infrastructure/sfn_util.py, source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py, source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py, source/tests/unit/infrastructure/test_stack.py
Implement nested distributed map (with locked concurrency) to iterate over the ordered inventory stored in S3.
=> Implement nested distributed map over sorted inventory

source/refreezer/application/glacier_s3_transfer/download.py, source/refreezer/application/glacier_s3_transfer/upload.py, source/refreezer/application/glacier_service/glacier_apis.py, source/refreezer/application/handlers.py, source/refreezer/application/hashing/s3_hash.py, source/refreezer/application/mocking/handlers.py, source/refreezer/application/mocking/notify_sns.py, source/refreezer/pipeline/source.py, source/tests/conftest.py, source/tests/integration/infrastructure/conftest.py, source/tests/integration/infrastructure/sfn_util.py, source/tests/integration/infrastructure/test_archive_chunk_determination_lambda.py, source/tests/integration/infrastructure/test_async_facilitator.py, source/tests/integration/infrastructure/test_buckets.py, source/tests/integration/infrastructure/test_chunk_retrieval_lambda.py, source/tests/integration/infrastructure/test_glacier_object_retrieval_dynamodb.py, source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py, source/tests/integration/infrastructure/test_inventory_chunk_determination_lambda.py, source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py, source/tests/integration/infrastructure/test_retrieve_archive_step_function.py, source/tests/unit/application/glacier_s3_transfer/test_download.py, source/tests/unit/application/glacier_s3_transfer/test_upload.py, source/tests/unit/conftest.py, source/tests/unit/infrastructure/test_stack.py, source/tests/unit/mocking/test_mock_glacier_stack.py
Addressed Changes are grouped like below:
1 - Only typing imports are adjusted to use "from typing import X" format.
2 - If an import is deleted its because the dependency wasnt being used in the code.
3 - Very few lines of code are adjusted because of sonar lint warnings.
=> Update All the imports to decided standards for all code modules

source/refreezer/infrastructure/nested_distributed_map.py, source/refreezer/infrastructure/stack.py, source/tests/integration/infrastructure/test_retrieve_archive_step_function.py, source/tests/unit/infrastructure/test_stack.py
Add nested distributed map for archive processing
=> Add nested distributed map for archive processing

source/refreezer/infrastructure/stack.py, source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py, source/tests/unit/infrastructure/test_stack.py
https://app.asana.com/0/1202938635037719/1204274021865694/f
=> Inventory write multipart upload metadata

source/refreezer/infrastructure/stack.py, source/refreezer/mocking/mock_glacier_stack.py, source/tests/unit/infrastructure/test_stack.py
Add initiate job step for Archive retrieval
=> Add initiate job step for Archive retrieval
